ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - '@vercel/speed-insights'
  - argon2
  - esbuild
  - netlify-cli
  - prisma
  - protobufjs
  - sharp
  - unix-dgram
  - unrs-resolver
