#!/bin/bash

# Vercel Environment Variables Setup Script
# This script helps you set up environment variables on Vercel

echo "==================================="
echo "Vercel Environment Variables Setup"
echo "==================================="
echo ""
echo "Go to your Vercel project settings and add these environment variables:"
echo ""
echo "REQUIRED Variables:"
echo "-------------------"
echo "DATABASE_URL                     = Your PostgreSQL connection string"
echo "NEXTAUTH_SECRET                  = $(openssl rand -base64 32)"
echo "NEXTAUTH_URL                     = https://your-domain.vercel.app"
echo "GOOGLE_CLIENT_ID                 = Your Google OAuth Client ID"
echo "GOOGLE_CLIENT_SECRET             = Your Google OAuth Client Secret"
echo ""
echo "OPTIONAL Variables (for full functionality):"
echo "--------------------------------------------"
echo "# Redis Configuration"
echo "REDIS_HOST                       = Your Redis host"
echo "REDIS_PORT                       = 6379"
echo "REDIS_PASSWORD                   = Your Redis password"
echo ""
echo "# Email Service (SMTP)"
echo "EMAIL_FROM                       = noreply@vasquezlawfirm.com"
echo "SMTP_HOST                        = Your SMTP host"
echo "SMTP_PORT                        = 587"
echo "SMTP_USER                        = Your SMTP username"
echo "SMTP_PASSWORD                    = Your SMTP password"
echo ""
echo "# Payment Processing"
echo "STRIPE_SECRET_KEY                = Your Stripe secret key"
echo "STRIPE_WEBHOOK_SECRET            = Your Stripe webhook secret"
echo "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = Your Stripe publishable key"
echo ""
echo "# AI Services"
echo "OPENAI_API_KEY                   = Your OpenAI API key"
echo "ANTHROPIC_API_KEY                = Your Anthropic API key"
echo "RETELL_API_KEY                   = Your Retell AI API key"
echo ""
echo "# Voice & SMS Services"
echo "RETELL_API_KEY                   = Your Retell AI API key (for voice)"
echo "GHL_API_KEY                      = Your GoHighLevel API key (for SMS)"
echo "GHL_LOCATION_ID                  = Your GoHighLevel Location ID"
echo ""
echo "# Analytics"
echo "NEXT_PUBLIC_GA_MEASUREMENT_ID    = Your Google Analytics ID"
echo "NEXT_PUBLIC_POSTHOG_KEY          = Your PostHog API key"
echo "NEXT_PUBLIC_POSTHOG_HOST         = Your PostHog host"
echo ""
echo "# Error Tracking"
echo "SENTRY_DSN                       = Your Sentry DSN"
echo "NEXT_PUBLIC_SENTRY_DSN           = Your Sentry DSN (client-side)"
echo ""
echo "# Maps"
echo "NEXT_PUBLIC_GOOGLE_MAPS_API_KEY  = Your Google Maps API key"
echo ""
echo "==================================="
echo "Deployment URL Check"
echo "==================================="
echo ""
echo "Your deployment should be available at:"
echo "https://vlf-website.vercel.app"
echo "or"
echo "https://vlf-website-[team-name].vercel.app"
echo ""
echo "Check the Vercel dashboard for the exact URL."